spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 30000 # 5m
    refreshTokenExpiration: 6048000 # 7d
stripe:
    secretKey: ${STRIPE_SECRET_KEY}
websiteUrl: "http://localhost:4242"